### PR TITLE
finalize view: pass shop param to login if avaliable

### PR DESCRIPTION
**Pull request by mrk-its**
When Embedded App SDK is used and user opens application first time from admin panel login page is displayed in frame. This simple patch fixes it for us.

### CODE REVIEW

**Comment by gavinballard** [comment]
Thanks @mrk-its! I'll have a look at this ASAP and get it merged. :+1:

**Comment by gavinballard** [comment]
Hey @mrk-its, thanks again for taking the time to submit this PR.

I'm a little confused about the behaviour of this patch, so maybe you can help me out a bit. The redirect to the login URL you've added is only taking place when the `finalize` call has failed to extract an API token during the OAuth flow - this shouldn't be happening in the normal flow of events.

The changes I made in [this commit](https://github.com/discolabs/django-shopify-auth/commit/d040c4ba267f9df1fb8c74ce5fb8452463ae3bc5) will automatically handle the passing of Shopify's authentication parameters (`shop`, `timestamp`, and `signature`) to the start of the login flow for any view wrapped in the `@login_required` decorator that's accessed without a logged in user. Shopify passes all of these parameters with every request, so if you're trying to access a login-protected part of your app from within the Admin (say, `/dashboard`), there should be an automatic redirection to the login page (with the authentication parameters intact), which will go through the login flow and finally return you to `/dashboard`.

Hopefully that all made sense - perhaps I'm just not quite understanding the issue you were having. If you could provide more detail, that would be great!

Thanks!

**Comment by mrk-its** [comment]
Hey.

I've checked things on our side again and it turned out that this issue was caused by invalid application callback URL (it was set to finalize view) - after change to application main view everything works as expected :)

Thanks for fast reply - it was very helpful.

**Comment by mrk-its** [comment]
BTW - Can you take a look at https://ecommerce.shopify.com/c/shopify-apis-and-technology/t/sorting-items-in-collections-via-api-224246 ? Thanks !

**Comment by gavinballard** [comment]
Great, glad that works @mrk-its :).

**Pull request closed without merging**
