### PR TITLE
Django 2.0 Updates

### PR DESCRIPTION
**Pull request by aphelionz**
Just made these small changes to my install of this package and got it to work with Django 2.0... at least for the primary use case.

### CODE REVIEW

**Comment by Benoss** [comment]
This is not compatible with Django 1.8 (End of life April 2018)
Maybe would be wise to release Django 2.0 support with the 1.0 release of django-shopify-auth and have 1.8 and python2.7 compatibility for versions <1.0

**Comment by aphelionz** [comment]
Sounds reasonable!

**Comment by dlo** [comment]
Would be great to get this merged!

**Comment by dlo** [comment]
I added backwards compatible support in #41 along with a few other fixes.

**Pull request closed without merging**
