### PR TITLE
fix #56: request.user is incorrect when using several shop on same client browser

### LINKED ISSUE #56: request.user is incorrect when using several shop on same client browser
When using several shop in the same browser, request.user is set incorrectly (cookie is the same).
I will try to look at this bug, this is because the app use session auth I think. We need to user hmac auth.

### PR DESCRIPTION
**Pull request by boolangery**

### CODE REVIEW

**Comment by stlk** [comment]
Thanks for this PR! I'm curious, why did you decide to disable 3rd party cookie check? Do you have your own handling?

**Comment by boolangery** [comment]
I need maybe to put this in another PR. Actually, 3rd party cookie check is breaking Shopify automatic review. See this message I received each time this cookie check was enabled:


> Requirements that must be met before initial screening
> --
> App must install successfully 
App not requesting access to shop immediately after clicking "Add App". Expected OAuth to be initiated during install or reinstall at https://appstoretest5.myshopify.com/admin/oauth/request_grant but was directed to https://app.com/accounts/login/.

When the app is reviewed/accepted by Shopify, its fine to enable it again in production.

**Comment by trev0r** [comment]
I had a similar problem and ended up putting the check into the login_required decorator, I'm not 100% sure if that would fix all use cases but it wouldn't require everyone adding middleware to fix this.

**Comment by stlk** [comment]
I agree with @trev0r. We should be solving this in decorator(feel free to contribute one) or mixin(just added one I'm using in https://github.com/discolabs/django-shopify-auth/commit/726e33882f4a4543caf7633ae3ef7774957ef8da). Closing this PR as I fixed the other issues separately. New release will come shortly. Thanks for nudging me to fix it 👍

**Pull request closed without merging**
